// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "huvoapi",
            "endpoint": "https://71wns773q6.execute-api.us-east-1.amazonaws.com/production",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:85198e4f-059d-4e93-8da6-3dfc57324fba",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aIQmty9wC",
    "aws_user_pools_web_client_id": "5m63dm5d0mu8m5dm025dmsc6ka",
    "oauth": {}
};


export default awsmobile;
